version: "3.8"
services:
  app:
    image: democrudapp
    container_name: flask_app
    ports:
      - "8099:8099"
    environment:
      - DB_HOST=10.0.2.15
      - DB_USER=satya
      - DB_PASSWORD=Shiva@1192
      - DB_NAME=student
    restart: unless-stopped